stages:
  - test

postman_tests:
  stage: test
  image:
    name: postman/newman
    entrypoint: ['']
  script:
    - newman --version
    - npm install -g newman-reporter-html
    - newman run TrainingDemo.postman_collection.json -e Production.postman_environment.json -d restful_booker.csv --reporters cli, html --reporter-html-export report.html
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - report.html
