stages:
  - test

postman_tests:
  stage: test
  image:
    name: postman/newman
    entrypoint: ['']
  script:
    - newman --version
    - newman run TrainingDemo.postman_collection.json -e Production.postman_environment.json -d restful_booker.csv
  # artifacts:
  #   expire_in: 1 week
  #   when: always
  #   paths:
  #     - report.html
