stages:
  - test

postman_tests:
  stage: test
  image:
    name: postman/newman
    entrypoint: ['']
  script:
    - newman --version
    - newman run TrainingDemo.postman_collection.json -e Production.postman_environment.json -d restful_booker.csv --reporters cli,junit --reporter-junit-export report.xml
  artifacts:
    expire_in: 1 week
    when: always
    reports:
      junit: report.xml
