stages:
  - test

postman_tests:
  stage: test
  image:
    name: postman/newman
    entrypoint: ['']
  script:
    - newman --version
  # artifacts:
  #   expire_in: 1 week
  #   when: always
  #   paths:
  #     - report.html
